name: 'demographics_pipeline'
version: '1.0.0'
config-version: 2

profile: 'demographics_pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  demographics_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
    audit:
      +materialized: view

seeds:
  demographics_pipeline:
    students_raw:
      +column_types:
        year_path_started: integer
